name       : sane-backends
version    : 1.0.24
release    : 1
source     :
    - https://sources.archlinux.org/other/sane/sane-backends-1.0.24.tar.gz : 27c7085a54f1505d8b551e6f1e69d30e1ee57328b18429bb2225dabf4c45462d
license    : custom
#See http://www.sane-project.org/LICENSE
summary    : Scanner Access Now Easy
description: |
    Scanner Access Now Easy
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
