name       : sane-backends
version    : 1.0.29
release    : 10
source     :
    - https://gitlab.com/sane-project/backends/uploads/54f858b20a364fc35d820df935a86478/sane-backends-1.0.29.tar.gz : aa027b4e5f59849cd41b8c26d54584cf31fffd986049019be6ad4140e11ea8ed
license    : GPL-2.0-only
homepage   : http://www.sane-project.org/
summary    : Scanner Access Now Easy
component  : desktop.util
description: |
    SANE stands for Scanner Access Now Easy. This package contains the SANE libraries (this means backends and network scanning parts) and the command line frontend scanimage.
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(libgphoto2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - cups-devel
    - libieee1284-devel
    - net-snmp-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Added-hpaio-to-backend-dll.conf.in.patch
    %configure --enable-avahi \
               --disable-locking
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 $pkgfiles/saned.sysusers $installdir/%libdir%/sysusers.d/saned.conf
    install -Dm00644 tools/udev/libsane.rules $installdir%libdir%/udev/rules.d/68-sane-backends.rules
    install -Dm00644 $pkgfiles/saned.socket   $installdir%libdir%/systemd/system/saned.socket
    install -Dm00644 $pkgfiles/saned@.service $installdir%libdir%/systemd/system/saned@.service
