name       : sane-backends
version    : 1.0.25
release    : 4
source     :
    - http://fossies.org/linux/misc/sane-backends-1.0.25.tar.gz : a4d7ba8d62b2dea702ce76be85699940992daf3f44823ddc128812da33dc6e2c
license    : GPL-2.0
summary    : Scanner Access Now Easy
component  : desktop.util
description: |
    Scanner Access Now Easy
builddeps  :
    - cups-devel
    - libieee1284-devel
    - libjpeg-turbo-devel
    - net-snmp-devel
    - pkgconfig(avahi-core)
    - pkgconfig(libgphoto2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
setup      : |
    %patch -p1 < $pkgfiles/0001-Added-hpaio-to-backend-dll.conf.in.patch
    %configure --enable-avahi \
               --enable-libusb_1_0
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/doc $installdir/usr/share/.
