name       : sane-backends
version    : 1.0.24
release    : 2
source     :
    - https://sources.archlinux.org/other/sane/sane-backends-1.0.24.tar.gz : 27c7085a54f1505d8b551e6f1e69d30e1ee57328b18429bb2225dabf4c45462d
license    : GPL-2.0
summary    : Scanner Access Now Easy
component  : desktop.util
description: |
    Scanner Access Now Easy
builddeps  :
    - cups-devel
    - libieee1284-devel
    - libjpeg-turbo-devel
    - net-snmp-devel
    - pkgconfig(avahi-core)
    - pkgconfig(libgphoto2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
setup      : |
    %configure --enable-avahi \
               --enable-libusb_1_0
build      : |
    %make
install    : |
    %make_install
