name       : sane-backends
version    : 1.0.27
release    : 7
source     :
    - https://alioth.debian.org/frs/download.php/latestfile/176/sane-backends-1.0.27.tar.gz : 293747bf37275c424ebb2c833f8588601a60b2f9653945d5a3194875355e36c9
license    : GPL-2.0
summary    : Scanner Access Now Easy
component  : desktop.util
description: |
    Scanner Access Now Easy (SANE) is a universal scanner interface.
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(libgphoto2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - cups-devel
    - libieee1284-devel
    - libjpeg-turbo-devel
    - net-snmp-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Added-hpaio-to-backend-dll.conf.in.patch
    %configure --enable-avahi \
               --disable-locking
build      : |
    %make
install    : |
    %make_install

    install -D -m644 $pkgfiles/saned.sysusers $installdir/%libdir%/sysusers.d/saned.conf
    install -D -m644 tools/udev/libsane.rules $installdir%libdir%/udev/rules.d/68-sane-backends.rules
    install -D -m644 $pkgfiles/saned.socket $installdir%libdir%/systemd/system/saned.socket
    install -D -m644 $pkgfiles/saned@.service $installdir%libdir%/systemd/system/saned@.service
