name       : sane-backends
version    : 1.0.30
release    : 12
source     :
    - https://gitlab.com/sane-project/backends/uploads/c3dd60c9e054b5dee1e7b01a7edc98b0/sane-backends-1.0.30.tar.gz : 3f5d96a9c47f6124a46bb577c776bbc4896dd17b9203d8bfbc7fe8cbbcf279a3
license    : GPL-2.0-only
homepage   : http://www.sane-project.org/
summary    : Scanner Access Now Easy
component  : desktop.util
description: |
    SANE stands for Scanner Access Now Easy. This package contains the SANE libraries (this means backends and network scanning parts) and the command line frontend scanimage.
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(libgphoto2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l2)
    - cups-devel
    - libieee1284-devel
    - net-snmp-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Added-hpaio-to-backend-dll.conf.in.patch
    %configure --enable-avahi \
               --disable-locking
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 $pkgfiles/saned.sysusers $installdir/%libdir%/sysusers.d/saned.conf
    install -Dm00644 tools/udev/libsane.rules $installdir%libdir%/udev/rules.d/68-sane-backends.rules
    install -Dm00644 $pkgfiles/saned.socket   $installdir%libdir%/systemd/system/saned.socket
    install -Dm00644 $pkgfiles/saned@.service $installdir%libdir%/systemd/system/saned@.service
